### ISSUE TITLE
Error while running isopret - "Could not find HGNC file"

### ISSUE THREAD

**Issue by justaddcoffee** [TheJacksonLaboratory/isopret#109]
On MacOS 11.5.2, brew install'd java (ended up with java 18 not 17, not sure if that is related). 

Started isopret like this:
`/usr/local/Cellar/openjdk/18/bin/java -jar isopret.jar`

Used the UI to download data sources, downloaded [this](https://zenodo.org/record/5880976/files/SRP251704_52.txt?download=1) HBA deals file, used the default Gene Ontology settings ("term for term" and "Bonferroni").

When I click analyze, it seems to find some of the downloaded files (some GO files, maybe some others), but then I see this runtime exception:

```
org.jax.isopret.core.except.IsopretRuntimeException: Could not find HGNC file at /Users/jtr4v/PycharmProjects/isopret/data/hgnc_complete_set.txt. Did you run the download command?
at org.jax.isopret.core.hgnc.HgncParser.<init>(HgncParser.java:92)
at org.jax.isopret.gui.service.IsopretDataLoadTask.call(IsopretDataLoadTask.java:163)
at org.jax.isopret.gui.service.IsopretDataLoadTask.call(IsopretDataLoadTask.java:38)
at javafx.concurrent.Task$TaskCallable.call(Task.java:1426)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.lang.Thread.run(Thread.java:833)
```

I possibly downloaded the files to the wrong place or something?

**Comment by pnrobinson** [comment]
Not sure but my best guess is that this was a network issue. I will be releasing what will be our submission version in a few hours, please just try again with that!

**Comment by pnrobinson** [comment]
@justaddcoffee -- could you give this another try with the latest release version? I fixed a few items in the GUI that are intended to make sure that all required files are actually downloaded before you can start the analysis (otherwise, you need to re-click the download button to continue the download -- it should work for all cases except if a file is corrupted during the download, which is much harder to check for).
PS, ,see the ReadTheDocs (available from the link on the main page) for some example files.

**Comment by justaddcoffee** [comment]
Yes, this works fine now, thanks!
