### ISSUE TITLE
Enriched terms that are not in inputs

### ISSUE THREAD

**Issue by karleg** [TheJacksonLaboratory/isopret#110]
Some terms appear in the enrichment results although they don't appear at all in the input files, for example:  GO:0000912
This occurs after I already replaced the wrong MF file with the right one, so it must come from somewhere else

**Comment by pnrobinson** [comment]
It is impossible to check this without more information, but it is expected behavior that terms can be found to be enriched because of the true-path rule -- an annotation to a term implies an annotation to all of its ancestors. This means that if there are annotations to many different descendants of a term, the term can be significant even though it is not explicitly used for annotations.
This is by far the most likely explanation.
